stages:
  data_ingestion:
    cmd: python src/Weather_Image_Classification/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Weather_Image_Classification/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Agricultural-crops



  prepare_base_model:
    cmd: python src/Crop_Image_Classification/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/Crop_Image_Classification/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDED_TOP
      - CLASSES
      - LEARNING_RATE
      - WEIGHTS

    outs:
      - artifacts/prepare_base_model