artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Viral3899/data/raw/main/Crops.zip
  # source_URL : D:/Weather_classification/Weather-Image-Classification/Weather.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion